# Generated by Django 4.2.7 on 2023-11-25 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('edad', models.IntegerField(max_length=99, validators=[django.core.validators.MaxValueValidator(99)])),
            ],
        ),
    ]
